### ISSUE TITLE
sample of data format

### ISSUE THREAD

**Issue by fred2008** [freesunshine0316/neural-graph-to-seq-mp#1]
hi, @freesunshine0316

Thank you for sharing the code.

Could you please share the sample of "2m.json" & "dev.json" in order to know json data format ?

**Comment by freesunshine0316** [comment]
Hi, @fred2008 
Thanks for being interested in our work. 
I've updated our readme file by including a sample.

**Comment by fred2008** [comment]
Thanks for your prompt reply.
