### ISSUE TITLE
Questions about Finetune

### ISSUE THREAD

**Issue by Cartus** [freesunshine0316/neural-graph-to-seq-mp#10]
Hi,

Thank you so much for sharing the code of this great work!

May I ask a question about the finetune process? Though I went through the paper (Konstas et al., 2017) and the Readme, I am still confused.

Is it like you use the large-scale automatic AMRs to pretrain the model, then save the model after each epoch, then use the gold AMRs to train the saved model? Then we can select the final model from these finetuned models based on the performance on the dev set.  Another question is about the pretraining part. Is it necessary to use early stopping strategy, like we only pretrain a few epochs like 10, cuz the pretraining dataset is huge?

Thanks again!

**Comment by freesunshine0316** [comment]
https://github.com/freesunshine0316/neural-graph-to-seq-mp/blob/master/src_g2s/G2S_trainer.py#L240
Lines 240 to 270 shows our pretraining and fine tuning process.

**Comment by Cartus** [comment]
I see.

Thank you so much for the prompt reply!

**Comment by Fije** [comment]
@freesunshine0316, is it true that it is possible to finetune with my own AMR's on your pretrained model (on the 2m for example)? I believe I've noticed your model checks for existing pretrained models in log_g2s, so I wonder if it is indeed just a matter of downloading your pretrained model and putting it in the right folder. Many thanks!
