### ISSUE TITLE
Extracting vocabulary

### ISSUE THREAD

**Issue by Fije** [freesunshine0316/neural-graph-to-seq-mp#13]
Hi, when extracting the vocabulary of your data, do we need to extract all words into 1 file (train,test,dev,finetune?)?

**Comment by freesunshine0316** [comment]
Hi, you can use the vocabulary from our released model.

**Comment by Fije** [comment]
Thank you. Why I was wondering about it, is because I wanted to see if I could use this code to build a style transfer experiment. So my source AMR's actually do not have the same words as the target sentences I align them with. 

Do you reckon it would work if I just concatenate the words from my target language when extracting the vocabulary? Would the copy mechanism be able to work with that? The words it copies (names, time descriptions etc. are probably not part of the style of the other 'style' anyway, right?) Or would you advice me to turn to the other paper+ code you sent me (your work on using semantics for NMT)?

**Comment by freesunshine0316** [comment]
If I understand correctly, each instance of your data is still a pair of (AMR, sentence), except that the sentence is in another language or another style. If it's true, I think this code fits better. It's very possible that you have to close the copy mechanism, and you just need change the corresponding switch in config file. For vocabulary, I recommendation is extracting separate vocabs for source and target. You have to change my code a little bit, but it's super easy.

**Comment by Fije** [comment]
Ok! Thank you so much for your suggestion. I will try to do that then! Why do you think this code works better than you semantic-nmt code? I could add the source sentences to the source AMR's to make it fit, if that's the problem. Thank you!!

**Comment by freesunshine0316** [comment]
I thought your inputs only have AMRs. If your inputs also contain sentences, then semantic-nmt code should be better.

**Comment by Fije** [comment]
Hi,

When using your script 2_generate_vocab, it adds punctuation to words, s.t. for example

'strength'
'strength:
'strength,'

are all unique words in the vocabulary. Is that on purpose? I thought I should probably change it to keep a smaller vocabulary. 
I was also wondering, the script produces 3 vocabularies, one for the words, one for the nodes and  one with edges. What do you do with the files for the nodes & edges? Did you put them all together and THEN extract the embeddings?

Thank you for all your help concerning your code!

**Comment by freesunshine0316** [comment]
@Fije Hi, It's not by that script. I think the real reason is that you didn't tokenize your data before running these scripts. Here is the source code of 2_generate_vocab.py, where no line adds any punctuations.
https://github.com/freesunshine0316/neural-graph-to-seq-mp/blob/master/data/2_gen_vocab.py
