### ISSUE TITLE
How is BLEU calculated?

### ISSUE THREAD

**Issue by leoribeiro** [freesunshine0316/neural-graph-to-seq-mp#14]
Hi @freesunshine0316 ,
Thank you for sharing your model. 

I was reading the file metric_utils.py that you created to calculate some BLEU scores (Bleu(4),["Bleu_1","Bleu_2","Bleu_3","Bleu_4"]). 

How do you calculate the BLEU scores in the paper? Do you average BLEU 1, 2, 3 and 4 and show this in tables 1 and 2?

**Comment by freesunshine0316** [comment]
Hi, metric_utils.py is not relevant for this project. It was just used for some reinforcement training, which we don't use in this paper. To make evaluation, you need to first run decode_g2s.sh, then use multi-bleu.perl from [Moses](https://github.com/moses-smt/mosesdecoder) to evaluate it.
