### ISSUE TITLE
Encoding AMR like a graph

### ISSUE THREAD

**Issue by antonionetoo** [freesunshine0316/neural-graph-to-seq-mp#16]
Reading your paper and seeing the code, I interested the part that you encode de AMR in the graph before the input of neural netword.
Is there any form to use just this part? The encode de AMR in the graph? Because I will use this representation (AMR like a graph, not serialized) in the other case.

Thanks.

**Comment by freesunshine0316** [comment]
Hi, 

   Do you mean encoding AMRs with our graph encoder? You can simply take the files [graph_encoder_utils.py](https://github.com/freesunshine0316/neural-graph-to-seq-mp/tree/master/src_g2s/graph_encoder_utils.py) and [G2S_data_stream.py](https://github.com/freesunshine0316/neural-graph-to-seq-mp/tree/master/src_g2s/G2S_data_stream.py)
