### ISSUE TITLE
Get None as output

### ISSUE THREAD

**Issue by Gitsamshi** [freesunshine0316/neural-graph-to-seq-mp#2]
Hello, I really like your work. I download your pretrained model,  and dump the your sample into json format. By directly running your script, I meet with the error below
Traceback (most recent call last):
  File "src_g2s/G2S_beam_decoder.py", line 347, in <module>
    outfile.write(cur_batch.id[0] + "\n")
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
It seems that we have not get any valid output after beamsearch.

My cmd line: CUDA_VISIBLE_DEVICES=2 ./decode_g2s.sh silver_2m
Code to form json file: 
a = [{"amr": "describe :arg0 ( person :name ( name :op1 ryan )  )  :arg1 person :arg2 genius",
"sent": "ryan's description of himself: a genius."}]
with open('data/test.json', 'w') as outfile:
    json.dump(a, outfile)

Meanwhile, since I don't have access to LDC corpus, is it also valid to convert the public little_prince dataset into your simplified format? l would really appreciate it if you can help me with it.

**Comment by freesunshine0316** [comment]
Hi, 

  Please add an "id" field to each instance in your json file.
  For instance,
a = [{"amr": "describe :arg0 ( person :name ( name :op1 ryan ) ) :arg1 person :arg2 genius",
"sent": "ryan's description of himself: a genius.",
"id": "0"}]

**Comment by Gitsamshi** [comment]
Issue solved, thank you
