### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by bjascob** [freesunshine0316/neural-graph-to-seq-mp#20]
I'm curious what type of GPU, how many and how long it took to train LDC2017T10?

I have available a single TitanX (a few generations old) and I'm wondering if this is sufficient to train on the newer (and larger) LDC2020T02.

**Comment by freesunshine0316** [comment]
I used Tesla X40 (12G memory). I doesn't take long if the model is trained only on the gold corpus.
I think TitanX can be sufficient, as I used to train the model with 2M silver data on an X40, and of course it took almost a week until the training is converged.
