### ISSUE TITLE
Pretrained Word Embeddings

### ISSUE THREAD

**Issue by lurr98** [freesunshine0316/neural-graph-to-seq-mp#24]
Hi, I was wondering if the pretrained word embeddings are still avaliable? I think, they're not in the google drive.
Thank you!

**Comment by freesunshine0316** [comment]
Thanks for pointing it out.
Though the word embeddings are jointly trained and are part of the trained model, our model does need the pretrained word embedding file to initialize the neural architecture (before loading the model). 
Here is the address for the embeddings https://drive.google.com/file/d/1XhCW0eI1PQY51o_gB_MyG1DKsOG0bjIu/view?usp=sharing

**Comment by lurr98** [comment]
Perfect, thank you lots!
