### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by Gitsamshi** [freesunshine0316/neural-graph-to-seq-mp#3]
I run your model on the corpus of the little prince and the results were quite good. Was little prince corpus already included in the training set?  Thank you

**Comment by freesunshine0316** [comment]
I don't think so. The only training data is the LDC2015E86 and 2 million raw data sampled from Gigaword, parsed by JAMR.

**Comment by lurr98** [comment]
@Gitsamshi do you happen to know the bleu score on the little prince corpus you got? I'm getting a score of 33.25 on the testset but only 13.5 on the little prince corpus, so I'm not sure if something went wrong while preprocessing the corpus
