### ISSUE TITLE
2016 dataset

### ISSUE THREAD

**Issue by miguelballesteros** [freesunshine0316/neural-graph-to-seq-mp#4]
Hi, I'm trying to use the simplifier in LDC2016 data but I get 6 errors with an obscure message: "Program should never enter here!"
and then it crashes

This is the log:

`Program should never enter here !

(h / hope-01 :ARG0 (i / i) :ARG1 (k / know-01 :ARG0 (t / they) :ARG1 (t2 / thing :ARG2-of (m / mean-01 :ARG1 (s / string-entity :value "Auf Wiedersehen")))))
Program should never enter here !

(u / use-01 :ARG0 (y / you) :ARG1 (o / or :op1 (s / string-entity :value "compatible with") :op2 (f / fit-06) :op3 (f2 / for)) :location (b / before :op1 (n / name :mod (b2 / brand))) :location (t / title :poss (l / listing :poss y)) :purpose (d / describe-01 :ARG0 y :ARG1 (i / item :mod (o2 / or :op1 (c2 / compatible :mod (u2 / universal)) :op2 (c3 / compatible :prep-with (c4 / class :mod (p / product :quant (e / entire))))))))
Program should never enter here !

(b / bear-01 :ARG0 (t / thing :instrument-of (s / seal-01 :ARG0  (g  /  government-organization  :name  (n3  /  name  :op1  "Department"  :op2  "of"  :op3  "Justice") :mod  (c  /  country  :name  (n  /  name  :op1  "U.S."))))) :ARG1 (p / phrase-01 :ARG2 (s2 / string-entity :value "Qui Pro Domina Justitia Sequitur") :mod  (l2  /  language  :name  (n4  /  name  :op1  "Latin"))))
Program should never enter here !

(o / or :op2 (l / lose-02 :mode interrogative :ARG0 (c / curiosity :poss (y / you)) :ARG1 (s / steam-02 :ARG1 c) :time (s2 / see-01 :ARG0 y :ARG1 (s3 / string-entity :value "( R )"))))
Program should never enter here !

(h / have-03 :polarity - :ARG0 (h2 / he) :ARG1 (a / anything :mod (c / catchy :degree (e / equal) :compared-to (s / string-entity :value "hope and change")) :ARG0-of (h3 / hold-01 :ARG1 (i / interest-01 :ARG1 (y / you)))) :ARG1-of (f / fortunate-01 :polarity -))
Program should never enter here !

(a / and :op1 (o / obvious-01 :ARG1 (k / know-01 :polarity - :ARG0 (y / you :mod (s / someone :ARG0-of (h / have-03 :ARG1 (s2 / string-entity :value "critical thinker") :location (a2 / avatar :poss s)))) :ARG1 (t / thing :ARG2-of (m / mean-01 :ARG1 s2)))))
Program should never enter here !

(s / say-01 :ARG0  (p  /  person :name (n / name :op1 "Bill" :op2 "Maher")) :ARG1 (b / base-02 :ARG1 (e / elect-01 :mod  (p2  /  political-party :name (n2 / name :op1 "Republican")) :mod (e2 / every)) :ARG2 (b2 / bullshit :mod (s2 / sentiment) :mod (s3 / some) :example (o / or :op1 (f / flag) :op2 (p3 / pin :mod (f2 / flag)) :op3  (p4  /  publication :name (n3 / name :op1 "Pledge" :op2 "to" :op3 "America")) :op4 (s4 / string-entity :value "It's morning in America"))) :time (l / long :degree (m / most))))
Program should never enter here !

(h / hyperlink-91 :ARG1 (s / say-01 :ARG0 (s2 / science :time (d / date-entity :decade 1970)) :ARG1 (t / thing :topic (c / cool-01 :ARG1 (g / globe)))) :ARG3 (u / url-entity :value "What 1970 s science said about global cooling"))
Exception in thread "main" java.lang.NumberFormatException: For input string: "pdf""
	at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.lang.Integer.parseInt(Integer.java:580)
	at java.lang.Integer.valueOf(Integer.java:766)
	at util.corpus.wrappers.AmrAlignment.parseAlignments(AmrAlignment.java:64)
	at util.corpus.wrappers.AmrAlignment.<init>(AmrAlignment.java:40)
	at util.corpus.wrappers.Amr.parse(Amr.java:101)
	at util.corpus.wrappers.Amr.<init>(Amr.java:33)
	at util.corpus.wrappers.AmrLinearize.<init>(AmrLinearize.java:31)
	at util.corpus.wrappers.AmrLinearizedSentence.parseAmr(AmrLinearizedSentence.java:53)
	at util.apps.AmrUtils.anonymizeSingleAmr(AmrUtils.java:147)
	at util.apps.AmrUtils.lambda$anonymizeFile$0(AmrUtils.java:117)
	at util.apps.AmrUtils$$Lambda$4/558638686.accept(Unknown Source)
	at java.util.Iterator.forEachRemaining(Iterator.java:116)
	at java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1801)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at util.apps.AmrUtils.anonymizeFile(AmrUtils.java:116)
	at util.apps.AmrUtils.anonymizeAmr(AmrUtils.java:76)
	at util.apps.AmrUtils.main(AmrUtils.java:651)`

**Comment by miguelballesteros** [comment]
and thanks! any help?

**Comment by freesunshine0316** [comment]
There shouldn’t be space within a string bounded by “”. You can replace space with “_”.

**Comment by freesunshine0316** [comment]
Hi, Miguel. Has the problem been solved?

**Comment by miguelballesteros** [comment]
not really, after replacing the spaces and putting hyphens, I get this

./anonDeAnon_java.sh anonymizeAmrFull true ../LDC2016E25_DEFT_Phase_2_AMR_Annotation_R2/split/training/training.nowiki.linearized.txt 
Exception in thread "main" java.lang.NumberFormatException: For input string: "pdf""

which I assume that your system is expecting a number and it encounters pdf;  currently looking for it in the dataset.

**Comment by miguelballesteros** [comment]
all "pdf"s are part of **url-entity : value "http...pdf"**
not sure why the system is complaining.

**Comment by freesunshine0316** [comment]
I'm not sure. It seems that your data has more noise. If the content isn't important, you can replace these with some placehoders. By the way, it's ":value" not ": value" right? There no space between the colon and value.

**Comment by miguelballesteros** [comment]
it is :value yes, I think that was github formatting my message.

The message is not really clear since it just complains about "pdf" but there is no single string with only pdf in the input.

This is the LDC2016 dataset, so it is standard and available. It is not an in-house version of the data.

**Comment by freesunshine0316** [comment]
It's wired, as I saw similar AMR structure in my dataset and there's no error reported. 
If they are not too many, maybe you can skip them for now.

**Comment by miguelballesteros** [comment]
Linfeng, can you share the way you linearize the sentences? If you used a script or some regex. It seems to be very sensitive to double spaces and things like that.

thank you,
Miguel

**Comment by freesunshine0316** [comment]
I simply use the simplifier. There are only 6 cases in my training set where there is a space inside "". I manually replace them with "_" first before running the simplifier.

**Comment by freesunshine0316** [comment]
You may send me a case and I can help you debugging with it. I'm working on my AAAI and TACL submissions, so I may not finish in a short time.

**Comment by miguelballesteros** [comment]
The simplifier requires linearized data, right?

**Comment by freesunshine0316** [comment]
Actually, the simplifier does the linearization too. It uses depth-first traversal. So the results contain the original graph structures.

**Comment by miguelballesteros** [comment]
If I use non linearized graphs as input I get 
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 9
	at util.corpus.wrappers.Amr.parse(Amr.java:100)
	at util.corpus.wrappers.Amr.<init>(Amr.java:33)

**Comment by freesunshine0316** [comment]
Hi, Miguel. 
The simplifier takes AMR files where an AMR graph takes exactly one line. The original AMRs take multiple lines, so you have to merge each of them into one line. If you need the code I can send it to you shortly.

**Comment by miguelballesteros** [comment]
Linfeng, I know that. That's what I meant with "linearize"

can you describe the process to produce AMR graphs in only one line? because I did that, but there are many different possibilities

**Comment by freesunshine0316** [comment]
I’ll send you my script later. It basically does the following thing. Given an AMR:
“
(w / want-01
        :ARG0 (b / boy)
        :ARG1 (g / go-01
                  :ARG0 b))
“
The result is 

(w / want-01 :ARG0 (b / boy) :ARG1 (g / go-01 :ARG0 b))

**Comment by miguelballesteros** [comment]
yeah, I did that with a couple of sed commands, but I wonder what I should do with double spaces and things like that.

**Comment by freesunshine0316** [comment]
I think the double space doesn’t cause the problem. You may replace with single space and manually replace spaces within “” with hyphens or underlines. 

If there is still the problem. Please send me the case

**Comment by miguelballesteros** [comment]
The problems are what I mentioned in this thread:

1. It complaints about double spaces in entities. I replaced them with "_'. It works. Although I don't like it, since I would need to put the spaces back later.
2. It complaints about url values, expecting a number when in the annotation we have "pdf" or "html". This looks like a bug.

If I filter out these 2 cases, then it produces an output, but I wonder what happened with the rest of urls that are very frequent in the dataset ~460 in total (out of 36500 sentences)

The usecase is to run it in the LDC2016 dataset.

Thanks for your help either way.

**Comment by freesunshine0316** [comment]
For 1. you can replace with any special tokens so that the spaces can be easily restored. I know it's annoying, but containing spaces within quotes violates the AMR guidelines.
For 2. I observed 31 similar situations in my corpus, such as "(u / url-entity :value "http://www.gao.gov/new.items/d10818.pdf")", but the simplifier doesn't crash for any of them. So I think the reason can be something else.
I don't have LDC2016 corpus, so would you please send me the exact case. Thanks.

**Comment by miguelballesteros** [comment]
The simplifier does not output anything, it just crashes and the line of code in which it happens. So I do not know which exact case is causing the issue. I just removed all lines with URLs and it worked.

About the spaces, this is the official ldc2016 dataset, so it is kind of interesting that they left things that violate the guidelines, but you are right.

**Comment by miguelballesteros** [comment]
Linfeng, do you have a way to map the simplified graphs back to AMR graphs. I know this might sound like useless, but if I make changes to the AMR graphs while they are simplified, it would be awesome to have a way to get an evaluable graph. Do you have something like this?

**Comment by freesunshine0316** [comment]
Sorry, I don't have. Simplification doesn't change the graph structure. It just removes the node variable. So it is possible to map each node back using a local context (itself, parent, children).

**Comment by miguelballesteros** [comment]
thanks!

**Comment by shashwath94** [comment]
Hi @freesunshine0316 ,
Could you send me the script for converting the default AMR format to single line format? I'm having the same issue and nothing seems to work. Thanks in advance!

**Comment by freesunshine0316** [comment]
Hi, @shashwath94 
Do you mean the original AMRs in the LDC file?
To do simplification from there, you first need to concatenate the multiple lines into a single line. That is simple and a python script can do it. I attach my script below. After converting into single-line AMRs, you can use our simplification script mentioned in the README file to simplify them. 

==========script is below==============

import sys

ids = []
id_dict = {}
amrs = []
amr_str = ''
for line in open(sys.argv[1],'rU'):
    if line.startswith('#'):
        if line.startswith('# ::id'):
            id = line.lower().strip().split()[2]
            ids.append(id)
            id_dict[id] = len(ids)-1
        continue
    line = line.strip()
    if line == '':
        if amr_str != '':
            amrs.append(amr_str.strip())
            amr_str = ''
    else:
        amr_str = amr_str + line + ' '

if amr_str != '':
    amrs.append(amr_str.strip())
    amr_str = ''

if len(sys.argv) == 3:
    for line in open(sys.argv[2],'rU'):
        id = line.lower().strip()
        print amrs[id_dict[id]]

**Comment by shashwath94** [comment]
Hi @freesunshine0316 ,
Thank you for the script. Since I do not have access to the LDC dataset, I'm using the one [here](http://www.let.rug.nl/rikvannoord/AMR/silver_data/all_camr_parsed_1250k.txt). Is the raw format of this dataset acceptable?

**Comment by freesunshine0316** [comment]
Hi, Yes.
It's basically the same format as LDC dataset. You have to first convert each AMR into a single line, then use simplification script described in the README file.

**Comment by freesunshine0316** [comment]
I've just uploaded the multi-line-to-single-line script into the repository

**Comment by shashwath94** [comment]
Thanks a lot @freesunshine0316 !
