### ISSUE TITLE
LDC2015E86

### ISSUE THREAD

**Issue by MingjieChen** [freesunshine0316/neural-graph-to-seq-mp#6]
Hi,

Is there any access to LDC2015E86 data?

Thanks

**Comment by freesunshine0316** [comment]
If your institute has the license of any later version of the AMR bank, I can send you the LDC2015E86 version.

**Comment by MingjieChen** [comment]
I am sorry, my institute only has license for a 2017 version.
Very grateful you could send me the LDC2015E86 version.
my email is mchen33@sheffield.ac.uk
Thanks

**Comment by Fije** [comment]
Hi,
Do I need to build/install anything first when trying to use the amr_simplifier code? (on MacOS)
Should I follow the build/install process of NeuralAMR first?

Thanks

**Comment by freesunshine0316** [comment]
@Fije I think you don't need to.

**Comment by Fije** [comment]
> @Fije I think you don't need to.

Many thanks.
