### ISSUE TITLE
Using zero for padding

### ISSUE THREAD

**Issue by MingjieChen** [freesunshine0316/neural-graph-to-seq-mp#7]
Hi,

Just a little question, not sure I am correct.
You are using "0" to pad maxtrix. But in maxtrix "in_neight_indices", there could be two kinds of "0".
One is padding "0", the other is the first node's indice (should be "0").
Should there be some problem if this conflicts of "0"?

Thanks

**Comment by freesunshine0316** [comment]
For neighborhood 0 is not associated with any embedding vectors, and we use a 3D mask for the neighborhoods. So it doesn't matter.
