### ISSUE TITLE
converting sparse to dense

### ISSUE THREAD

**Issue by MingjieChen** [freesunshine0316/neural-graph-to-seq-mp#8]
Hi， 

When I run your code, I have a user warning : 
```
UserWarning: Converting sparse IndexedSlices to a dense Tensor of unknown shape. This may consume a large amount of memory.
  "Converting sparse IndexedSlices to a dense Tensor of unknown shape. "
```

Meanwhile, the mem cost of this task boost up to  20,000 GB, and it is been killed by my machine.
Something wrong?

Thanks

**Comment by freesunshine0316** [comment]
This system may consume plenty of CPU memory, especially when using large-scale data, but it's not relevant to the warning.

**Comment by MingjieChen** [comment]
Understood, Thanks
